### ISSUE TITLE
rllib3.exceptions.ResponseError: too many 403 error responses

### ISSUE THREAD

**Issue by mlee33-nor** [Bunsly/HomeHarvest#104]
when i run the default code it works fine but if i change ANYTHING like the city even then it gives a 403 error raise

urllib3.exceptions.ResponseError: too many 403 error responses
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\Myles\PycharmProjects\pythonProject\.venv\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Myles\PycharmProjects\pythonProject\.venv\Lib\site-packages\urllib3\connectionpool.py", line 948, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Myles\PycharmProjects\pythonProject\.venv\Lib\site-packages\urllib3\connectionpool.py", line 948, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Myles\PycharmProjects\pythonProject\.venv\Lib\site-packages\urllib3\connectionpool.py", line 948, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Myles\PycharmProjects\pythonProject\.venv\Lib\site-packages\urllib3\connectionpool.py", line 938, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Myles\PycharmProjects\pythonProject\.venv\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.realtor.com', port=443): Max retries exceeded with url: /api/v1/rdc_search_srp?client_id=rdc-search-new-communities&schema=vesta (Caused by ResponseError('too many 403 error responses'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Myles\3D Objects\New folder\py\PyCharm 2023.3.4\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 6, in <module>
  File "C:\Users\Myles\PycharmProjects\pythonProject\.venv\Lib\site-packages\homeharvest\__init__.py", line 60, in scrape_property
    results = site.search()
              ^^^^^^^^^^^^^
  File "C:\Users\Myles\PycharmProjects\pythonProject\.venv\Lib\site-packages\homeharvest\core\scrapers\realtor\__init__.py", line 439, in search
    result = self.general_search(search_variables, search_type=search_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Myles\PycharmProjects\pythonProject\.venv\Lib\site-packages\homeharvest\core\scrapers\realtor\__init__.py", line 355, in general_search
    response = self.session.post(self.SEARCH_GQL_URL, json=payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Myles\PycharmProjects\pythonProject\.venv\Lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Myles\PycharmProjects\pythonProject\.venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Myles\PycharmProjects\pythonProject\.venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Myles\PycharmProjects\pythonProject\.venv\Lib\site-packages\requests\adapters.py", line 691, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='www.realtor.com', port=443): Max retries exceeded with url: /api/v1/rdc_search_srp?client_id=rdc-search-new-communities&schema=vesta (Caused by ResponseError('too many 403 error responses'))

**Comment by mlee33-nor** [comment]
getting this ever time i try to gen a csv - its worked well over the last 3 months but having issues today

**Comment by mlee33-nor** [comment]
seems to be a proxy issue but i cant find any that work - do you have reccomendation for a working proxy with pycharm / this instance

**Comment by mlee33-nor** [comment]
when i run the default code it works fine but if i change ANYTHING like the city even then it gives a 403 error

**Comment by cullenwatson** [comment]
whats your search?

**Comment by cullenwatson** [comment]
Use proxy. Do @retry from tenacity, many ways around this
